### ISSUE TITLE
google-service.xml not found

### ISSUE THREAD

**Issue by Santoshah** [blakgeek/cordova-plugin-firebase-auth#7]
` cordova build android
Android Studio project detected
(node:1468) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'D:\wamp\www\fix\platforms\android\res\values\google-services.xml'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at updateStringsXml (D:\wamp\www\fix\plugins\cordova-plugin-firebase-core\hooks\configure-android.js:76:12)
    at module.exports (D:\wamp\www\fix\plugins\cordova-plugin-firebase-core\hooks\configure-android.js:24:9)
    at runScriptViaModuleLoader (C:\Users\Santosh\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:188:18)
    at runScript (C:\Users\Santosh\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:164:16)
    at C:\Users\Santosh\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:132:20
    at _fulfilled (C:\Users\Santosh\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\Santosh\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\Santosh\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:749:13)
(node:1468) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1468) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by ciriousjoker** [comment]
Same issue here.

It's interesting that it searches for android/res and not android/app/res.

I fixed it by creating `android/res/values` and executed `cordova run android` again. It copied the file to the useless location and was happy about it.


EDIT: LOL I just realized I had the same issue with a different of his plugins. My fix worked for cordova-plugin-firebase-messaging, so it might not work for you, but knowing how code is usually copypasted between projects, I'd say you've got a good chance it does :)
Good luck!

**Comment by ciriousjoker** [comment]
Nevermind, my "fix" didn't work the second time I installed the plugin... I'm confused now. Same issue with the other plugin now.
